### ISSUE TITLE
Error in HA log regarding parity history parsing - invalid literal for int() with base 10

### ISSUE THREAD

**Issue by ond000** [domalab/ha-unraid#39]
**Describe the bug**
In HA log i can see this error:

```
Logger: custom_components.unraid.coordinator
Zdroj: custom_components/unraid/coordinator.py:865
integrace: UNRAID (dokumentace, problémy)
První výskyt: 16:58:03 (1409 výskyty)
Naposledy logováno: 17:16:11

Error parsing parity history line '2024 Sep 9 02:23:50|18548|25.9 MB/s|0|0|check P Q|468850520|95023|2|Scheduled Non-Correcting Parity-Check': invalid literal for int() with base 10: '25.9 MB/s'
Error parsing parity history line '2024 Oct 14 02:29:20|18898|25.4 MB/s|0|0|check P Q|468850520|95354|2|Scheduled Non-Correcting Parity-Check': invalid literal for int() with base 10: '25.4 MB/s'
Error parsing parity history line '2024 Oct 28 02:31:54|19032|25.2 MB/s|0|0|check P Q|468850520|95508|2|Scheduled Non-Correcting Parity-Check': invalid literal for int() with base 10: '25.2 MB/s'
Error parsing parity history line '2024 Dec 16 02:38:22|19439|24.7 MB/s|0|0|check P Q|468850520|95895|2|Scheduled Non-Correcting Parity-Check': invalid literal for int() with base 10: '24.7 MB/s'
Error parsing parity history line '2024 Dec 22 17:54:15|18240|26.3 MB/s|0|0|check P Q|468850520|18240|1|Automatic Correcting Parity-Check': invalid literal for int() with base 10: '26.3 MB/s'
Traceback (most recent call last):
  File "/config/custom_components/unraid/coordinator.py", line 865, in _parse_parity_history
    speed_bytes = int(fields[2])
ValueError: invalid literal for int() with base 10: '68.7 MB/s'
```

**Expected behavior**

**Screenshots**

**Unraid (please complete the following information):**
 - Versions 6.12.13 and 6.2.14

**Home Assistant (please complete the following information):**
 - Version 2024.12.5

**Home Assistant installation type (please complete the following information):**
- \[ ] Docker / Container  
- \[ ] Virtual Machine
- \[x] Raspberry Pi

**Priority of Request**
- \[ ] High  
- \[ ] Medium  
- \[x] Low  

**Additional context**

**Comment by domalab** [comment]
Thanks for the info. Helps a lot. 

Code needs some tuning 😃

**Comment by domalab** [comment]
I made some updates today. Feel free to download latest source code, overwrite your existing unraid integration and restart home assistant.

**Comment by ond000** [comment]
I just did it, replaced all files by files downloaded from Git, looks like things are moving forward 😊 I just got different error:

```
Logger: custom_components.unraid.coordinator
Zdroj: custom_components/unraid/coordinator.py:656
integrace: UNRAID (dokumentace, problémy)
První výskyt: 18:39:37 (236 výskyty)
Naposledy logováno: 18:39:58

Error parsing parity history line '2024 Aug 22 07:02:37|39935|100.2 MB/s|0|0|recon D3|3907018532|39935|1|Parity Sync/Data Rebuild': Could not parse speed string '100.2 MB B': Invalid speed format: 100.2 MB B
Error parsing parity history line '2024 Aug 22 16:54:25|34564|115.8 MB/s|0|14698|check P Q|3907018532|34564|1|Manual Correcting Parity-Check': Could not parse speed string '115.8 MB B': Invalid speed format: 115.8 MB B
Error parsing parity history line '2024 Aug 27 03:26:17|35770|111.8 MB/s|0|0|check P Q|3907018532|185170|3|Scheduled Non-Correcting Parity-Check': Could not parse speed string '111.8 MB B': Invalid speed format: 111.8 MB B
Error parsing parity history line '2024 Sep 4 01:19:45|39877|100.3 MB/s|0|0|check P Q|3907018532|263979|4|Scheduled Non-Correcting Parity-Check': Could not parse speed string '100.3 MB B': Invalid speed format: 100.3 MB B
Error parsing parity history line '2024 Dec 23 10:21:40|45753|87.4 MB/s|0|5|check P Q|3907018532|45753|1|Automatic Correcting Parity-Check': Could not parse speed string '87.4 MB B': Invalid speed format: 87.4 MB B
Traceback (most recent call last):
  File "/config/custom_components/unraid/helpers.py", line 626, in parse_speed_string
    raise ValueError(f"Invalid speed format: {speed_str}")
ValueError: Invalid speed format: 68.7 MB B

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/unraid/coordinator.py", line 656, in _parse_parity_history
    speed_bytes = parse_speed_string(f"{fields[2]} B/s")
  File "/config/custom_components/unraid/helpers.py", line 638, in parse_speed_string
    raise ValueError(f"Could not parse speed string '{speed_str}': {err}")
ValueError: Could not parse speed string '68.7 MB B': Invalid speed format: 68.7 MB B

```

**Comment by domalab** [comment]
@ond000 I made a few updates to handle parity history line validation and handle edge cases.

Can you please test and let me know it works?

If not can, you please send me parity-logs as mine is very limited to only 2 recent parity runs.

cat /boot/config/parity-checks.log

**Comment by ond000** [comment]
Both parity check history errors disappear, but now I have another error:

```
Logger: custom_components.unraid.coordinator
Zdroj: custom_components/unraid/coordinator.py:661
integrace: UNRAID (dokumentace, problémy)
První výskyt: 23:13:35 (6 výskyty)
Naposledy logováno: 23:13:43

Could not parse speed value: Unavailable - Could not parse speed string 'Unavailable': Invalid speed format: Unavailable
```

**Comment by ond000** [comment]
Thanks for that @domalab now I don't have any error regarding parity check history, so from my point of view it looks fixed 😊
